default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

mysql2: &mysql2
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

test:
  <<: *mysql2
  database: posify_test

development:
  <<: *mysql2
  database: posify_dev

production:
  <<: *mysql2
  database: posify_prod
